### ISSUE TITLE
Does FlutterOggPiano work on iOS?

### ISSUE THREAD

**Issue by JimTompkins** [MandarinSmell/FlutterOggPiano#1]
First, thanks for a very useful package!  After trying flutter_midi, audio players/audiocache and sound pool, I found that FlutterOggPiano was the only one to give low latency audio on Android.

When I run the app on iOS, I get this exception:

2021-09-13 10:29:07.126448-0300 Runner[11498:736828] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method load on channel flutter_ogg_piano)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      FlutterOggPiano.load (package:flutter_ogg_piano/flutter_ogg_piano.dart:31:28)
<asynchronous suspension>

Should flutterOggPiano work on iOS?

Thanks!

**Comment by lukepighetti** [comment]
Related: https://github.com/MandarinSmell/FlutterOggPiano/pull/2
